name: Default Task Flow
version: "1.0"
description: Default workflow for processing tasks

# Global settings
settings:
  max_retries: 3
  timeout: 300
  parallel_execution: false

# Stages of task processing
stages:
  - name: initialization
    type: setup
    required: true
    actions:
      - load_configuration
      - initialize_agents
      - validate_environment

  - name: planning
    type: processing
    required: true
    actions:
      - analyze_task
      - create_execution_plan
      - validate_plan
    depends_on: initialization

  - name: execution
    type: processing
    required: true
    actions:
      - execute_plan
      - monitor_progress
      - handle_errors
    depends_on: planning

  - name: completion
    type: cleanup
    required: true
    actions:
      - validate_results
      - update_memory
      - cleanup_resources
    depends_on: execution

# Error handling
error_handling:
  retry_strategy:
    max_attempts: 3
    delay: 5
    exponential_backoff: true
  
  fallback_actions:
    - log_error
    - notify_admin
    - revert_changes

# Hooks for custom processing
hooks:
  pre_execution:
    - validate_requirements
    - check_resources
  
  post_execution:
    - save_results
    - cleanup_temporary_files

# Monitoring and logging
monitoring:
  metrics:
    - execution_time
    - memory_usage
    - error_rate
  
  logging:
    level: INFO
    handlers:
      - console
      - file 