# General settings
app:
  name: AI Agent System
  version: "1.0.0"
  environment: development
  debug: true

# Agent configuration
agents:
  planner:
    max_plan_steps: 10
    planning_timeout: 30
    validation_required: true
    
  executor:
    max_parallel_tasks: 4
    execution_timeout: 300
    retry_attempts: 3
    
  memory:
    max_short_term_size: 1000
    cleanup_interval: 3600
    persistence_enabled: true

# Tool settings
tools:
  web_search:
    rate_limit: 60
    cache_duration: 3600
    max_results: 10
    
  file_manager:
    allowed_extensions: [".txt", ".json", ".yaml", ".csv"]
    max_file_size: 10485760  # 10MB
    temp_dir: "/tmp/ai_agent"
    
  api_connector:
    timeout: 30
    max_retries: 3
    retry_delay: 5

# Workflow settings
workflow:
  default_flow: task_flow.yaml
  max_workflow_time: 3600
  parallel_execution: true
  error_handling:
    enabled: true
    max_retries: 3
    notification_email: admin@example.com

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/ai_agent.log
  max_size: 10485760  # 10MB
  backup_count: 5

# Security settings
security:
  api_key_required: true
  rate_limiting:
    enabled: true
    rate: 100
    period: 3600
  allowed_origins: ["localhost", "127.0.0.1"]

# Resource limits
resources:
  max_memory: "1G"
  max_cpu_percent: 80
  disk_space_limit: "10G"
  network_rate_limit: "5M" 