name: CI

on:
  push:
  pull_request:

jobs:
  python-style-ai-agent:
    name: ai_agent_project style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install formatters
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
      - name: Black check
        run: black --check ai_agent_project
      - name: isort check
        run: isort --profile black --check-only ai_agent_project
      - name: Flake8
        run: flake8 ai_agent_project

  python-compile:
    name: Python syntax compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Compile CoachAI
        run: python -m compileall CoachAI || true
      - name: Compile Project Starlink
        run: python -m compileall "Project Starlink" || true
      - name: Compile InterviewAgent
        run: python -m compileall InterviewAgent || true

  ai-agent-tests:
    name: ai_agent_project tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ai_agent_project/requirements.txt
      - name: Run pytest
        run: pytest -q ai_agent_project

  node-claudecode:
    name: ClaudeCode node checks (non-blocking)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: |
          cd ClaudeCode
          npm install
      - name: Test
        run: |
          cd ClaudeCode
          npm test
        continue-on-error: true

  python-style-coachai:
    name: CoachAI style checks (non-blocking)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install formatters
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
      - name: Black check
        run: black --check CoachAI
        continue-on-error: true
      - name: isort check
        run: isort --profile black --check-only CoachAI
        continue-on-error: true
      - name: Flake8
        run: flake8 CoachAI
        continue-on-error: true

  coachai-tests:
    name: CoachAI tests (smoke)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r CoachAI/requirements.txt
      - name: Run pytest
        run: pytest -q CoachAI

  project-starlink-style:
    name: Project Starlink style checks (non-blocking)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install formatters
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
      - name: Black check
        run: black --check "Project Starlink"
        continue-on-error: true
      - name: isort check
        run: isort --profile black --check-only "Project Starlink"
        continue-on-error: true
      - name: Flake8
        run: flake8 "Project Starlink"
        continue-on-error: true

  project-starlink-tests:
    name: Project Starlink tests (smoke)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r "Project Starlink/requirements.txt"
          pip install pytest
      - name: Run pytest
        run: pytest -q "Project Starlink"

  interviewagent-style:
    name: InterviewAgent style checks (non-blocking)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install formatters
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
      - name: Black check
        run: black --check InterviewAgent
        continue-on-error: true
      - name: isort check
        run: isort --profile black --check-only InterviewAgent
        continue-on-error: true
      - name: Flake8
        run: flake8 InterviewAgent
        continue-on-error: true

  mypy-ai-agent:
    name: mypy (ai_agent_project, non-blocking)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Run mypy
        run: mypy --ignore-missing-imports ai_agent_project
        continue-on-error: true

  mypy-coachai:
    name: mypy (CoachAI, non-blocking)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mypy and deps
        run: |
          python -m pip install --upgrade pip
          pip install mypy pydantic-settings
      - name: Run mypy
        run: mypy --ignore-missing-imports CoachAI
        continue-on-error: true

  interviewagent-tests:
    name: InterviewAgent tests (smoke)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r InterviewAgent/requirements.txt
      - name: Run pytest
        run: pytest -q InterviewAgent
